services:
  - type: web
    name: content-validation
    env: python
    buildCommand: "pip install -r Content_Validation/requirements.txt"
    startCommand: "python Content_Validation/app.py"
    envVars:
      - key: PORT
        value: "5000"
      - key: GOOGLE_APPLICATION_CREDENTIALS
        value: "/etc/secrets/graphology-ibm-firebase-adminsdk-eod85-4a2d7a2ea4.json"
    autoDeploy: true
    secretEnvVars:
      - key: GOOGLE_CREDENTIALS_JSON
        value: |
          {
            "type": "service_account",
            "project_id": "graphology-ibm",
            "private_key_id": "your-private-key-id",
            "private_key": "your-private-key",
            "client_email": "your-client-email",
            "client_id": "your-client-id",
            "auth_uri": "https://accounts.google.com/o/oauth2/auth",
            "token_uri": "https://oauth2.googleapis.com/token",
            "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
            "client_x509_cert_url": "your-client-x509-cert-url"
          }
