// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBiq_Sdpps9vAn29xxrB9-_Ejldpbv_SGU',
    appId: '1:164401328263:web:f3c16cc9e017f0da0b8822',
    messagingSenderId: '164401328263',
    projectId: 'graphology-ibm',
    authDomain: 'graphology-ibm.firebaseapp.com',
    storageBucket: 'graphology-ibm.appspot.com',
    measurementId: 'G-DPDNKWN2CC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtE1NcqZBijIJRLTyf0PoR-xIBt_-qcv8',
    appId: '1:164401328263:android:bb940ef7460572170b8822',
    messagingSenderId: '164401328263',
    projectId: 'graphology-ibm',
    storageBucket: 'graphology-ibm.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAaUI6uw6bDG0AB-Ij5CDO95YFpIo60RZU',
    appId: '1:164401328263:ios:f2ba4951711a7d3a0b8822',
    messagingSenderId: '164401328263',
    projectId: 'graphology-ibm',
    storageBucket: 'graphology-ibm.appspot.com',
    iosClientId: '164401328263-hv8ua2055es7puldvbfgqi7lq93v547v.apps.googleusercontent.com',
    iosBundleId: 'com.example.oneone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAaUI6uw6bDG0AB-Ij5CDO95YFpIo60RZU',
    appId: '1:164401328263:ios:f3910d02efa28b7f0b8822',
    messagingSenderId: '164401328263',
    projectId: 'graphology-ibm',
    storageBucket: 'graphology-ibm.appspot.com',
    iosClientId: '164401328263-5n5j7iqv1ogga5mt0to0hr87fnit6b75.apps.googleusercontent.com',
    iosBundleId: 'com.example.oneone.RunnerTests',
  );
}
